# this file setup various thinks that are for dev environment

x-api-base: &api-base
  build:
    context: .
    args:
      USER_UID: ${USER_UID:-1000}
      USER_GID: ${USER_GID:-1000}
  volumes:
    # mount code dynamically
    - "./app:/opt/open-prices/app"
    - ./pyproject.toml:/opt/open-prices/pyproject.toml
    # make doc generation available
    - ./mkdocs.yml:/opt/open-prices/mkdocs.yml
    - ./build_mkdocs.sh:/opt/open-prices/build_mkdocs.sh
    - ./README.md:/opt/open-prices/README.md
    - ./docs:/opt/open-prices/docs
    - ./gh_pages:/opt/open-prices/gh_pages
    # make migrations available so that we can run them easily
    - ./alembic:/opt/open-prices/alembic
    # mount tests
    - ./tests:/opt/open-prices/tests

services:
  api:
    <<: *api-base
    # uvicorn in reload mode
    command: ["gunicorn", "config.wsgi", "--bind", "0.0.0.0:8000", "--reload"]

  scheduler:
    <<: *api-base
    command: ["python", "manage.py", "qcluster"]
